spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/opsflow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${DB_PASSWORD}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 2s
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: /opsflow
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: auto
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1s
          multiplier: 2
          max-interval: 5s

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:720000000}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
