server:
  port: 8080

spring:
  application:
    name: opsflow
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/opsflow?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  flyway:
    baseline-on-migrate: false
    baseline-version: 1
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      timeout: 2s
opsflow:
  ticket:
    sla:
      scan-delay-ms: 300000

jwt:
  secret: opsflow-jwt-secret-key-for-development-2026
  expiration: 720000000

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true